### ISSUE TITLE
Odd Unresolved Symbols In Specific Circumstance

### ISSUE THREAD

**Issue by skl131313** [Ingrater/dmd#11]
What's strange is if you remove either function bigint1254 or bigint673, then the example compiles fine without incident. If the functions are compiled together however then they cause link errors.

The link errors when the functions are compiled in the same source are all templated functions. It seems a bit suspicious.

NOTE: adding export to these templated functions resolves the link error. But I don't think they should be exported, as they are templated. Shouldn't they be instigated in the exe? Which it seems is what happens when the two functions aren't compiled together, as they successfully link.

```D
import std.bigint;

// remove bigint1254 or bigint673 and no link errors occur.
void bigint1254()
{
    import std.array;
    import std.format;
    string[][] table ;
    auto w1 = appender!(char[]);
    foreach (entry; table)
    {
        immutable fmt = entry[0];
        formattedWrite(w1, fmt);
    }
}

void bigint673()
{
    import std.conv ;
    BigInt().to!int ;
}

void main()
{
}
```

The link errors:

```
main.obj : error LNK2019: unresolved external symbol _D3std5range10primitives52__T5doPutTS3std5array17__T8AppenderTAyaZ8AppenderTaZ5doPutFNaNbNfKS3std5array17__T8AppenderTAyaZ8AppenderKaZv referenced in function _D3std5range10primitives50__T3putTS3std5array17__T8AppenderTAyaZ8AppenderTaZ3putFNaNbNfKS3std5array17__T8AppenderTAyaZ8AppenderaZv
main.obj : error LNK2019: unresolved external symbol _D3std4conv16__T5parseThTAxaZ5parseFNaNfKAxaZh referenced in function _D3std6format18__T10FormatSpecTaZ10FormatSpec6fillUpMFNaNfZv
main.obj : error LNK2019: unresolved external symbol _D3std4conv16__T5parseTiTAxaZ5parseFNaNfKAxaZi referenced in function _D3std6format18__T10FormatSpecTaZ10FormatSpec6fillUpMFNaNfZv
main.obj : error LNK2019: unresolved external symbol _D3std9algorithm9searching41__T10startsWithVAyaa6_61203d3d2062TAxaTaZ10startsWithFNaNfAxaaZb referenced in function _D3std6format18__T10FormatSpecTaZ10FormatSpec6fillUpMFNaNfZv
main.obj : error LNK2019: unresolved external symbol _D3std4conv16__T5parseTkTAxaZ5parseFNaNfKAxaZk referenced in function _D3std6format18__T10FormatSpecTaZ10FormatSpec6fillUpMFNaNfZv
main.exe : fatal error LNK1120: 5 unresolved externals
Error: linker exited with status 1120
```

The most up to date exports is here if you need it:
https://github.com/sprinkle131313/phobos/tree/dll-export

**Comment by Ingrater** [comment]
Templates need to be exported. Dmd tries to reuse existing template instances. If dmd can infer statically that a specific template instance was already instanced by another module, this instance will be reused instead of instancing the template again. Consider the following simple example:

```
module lib;
import std.stdio;

export struct Foo(T)
{
  T value;
  void print() { writefln("%s", value); }
}

__gshared Foo!int g_inst = Foo!int(5);
```
```
module exe;
import lib;

void main(string[] args)
{
  auto f = Foo!int(5);
  f.print();
}
```

When compiling the exe dmd will look at the lib module and notice that the lib module already contains a instance of Foo!int. Therefor dmd will not instanciate Foo!int in the exe again. It will instead reuse the existing instance in the dll. But for this to work the template Foo needs to be export. Export in front of a tempalte basically means "In case you instanciate this template export the instance"

Another easy way to check if you are missing a export in front of a template is to compile the exe with "-allinst" if this fixes the issue then you are missing an export.

**Comment by Ingrater** [comment]
Any update on this issue from your end?

**Comment by skl131313** [comment]
Yah if it's suppose to be exported then that is what resolves it. But DMD doesn't seem very good at determining if an instance already exists.

```D
module lib;
import std.stdio;

struct Foo(T) // no export
{
  T value;
  void print() { writefln("%s", value); }
}

export void someFunc()
{
    static Foo!int g_inst = Foo!int(5);
    g_inst.print();
}
```
```D

module exe;
import lib;

void main(string[] args)
{
  auto f = Foo!int(5); // doesn't cause link error even tho it isnt exported.
  f.print();
  someFunc();
}
```
